# fly.toml app configuration file generated for lojatempback-dawn-brook-8400 on 2024-01-22T11:24:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lojatempback-dawn-brook-8400"
primary_region = "gru"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
