# fly.toml app configuration file generated for lojatempback on 2023-11-16T15:02:04-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lojatempback"
primary_region = "gru"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
